version: "3.9"

services:
  mf_drawer:
    build:
      context: ./mf_drawer
    ports:
      - "3001:8080"
    volumes:
      - ./mf_drawer/dist:/app/dist
    depends_on:
      - hall
    environment:
      - NODE_ENV=development

  mf_videos:
    build:
      context: ./mf_videos
    ports:
      - "3002:8080"
    volumes:
      - ./mf_videos/dist:/app/dist
    depends_on:
      - hall
    environment:
      - NODE_ENV=development

  hall:
    build:
      context: ./hall
    ports:
      - "8000:8080"
    volumes:
      - ./hall/dist:/app/dist
    environment:
      - NODE_ENV=development    

  bff:
    build: ./bff
    ports:
      - "3004:8080"
    volumes:
      - ./bff/src:/app/src
      - ./bff/dist:/app/dist
    environment:
      - NODE_ENV=development
