version: "3.9"

services:
  mf_drawer:
    image: sitalo/mfs-onlinegallery-mf_drawer:latest
    ports:
      - "3001:8080"
    environment:
      - NODE_ENV=production

  mf_videos:
    image: sitalo/mfs-onlinegallery-mf_videos:latest
    ports:
      - "3002:8080"
    environment:
      - NODE_ENV=production

  hall:
    image: sitalo/mfs-onlinegallery-hall:latest
    ports:
      - "8000:8080"
    environment:
      - NODE_ENV=production

  bff:
    image: sitalo/mfs-onlinegallery-bff:latest
    ports:
      - "3004:8080"
    environment:
      - NODE_ENV=production
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    env_file:
      - .env
